# Generated by Django 5.2.11 on 2026-03-07 15:07

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('profile_type', models.CharField(default='room', max_length=50)),
                ('area_square_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ceiling_height_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('floor_loading_capacity_psf', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dcim.location')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('location',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
