# Generated by Django 5.2.11 on 2026-03-12 23:00

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
        ('netbox_facilities', '0002_siteriskprofile_siteprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='total_building_area_sqft',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='_total_building_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='total_building_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='total_building_area_unit',
            field=models.CharField(blank=True, default='sqft', max_length=50),
        ),
        migrations.CreateModel(
            name='OperationalRequirementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hours_per_week', models.DecimalField(decimal_places=2, default=168, max_digits=5)),
                ('weeks_per_year', models.DecimalField(decimal_places=2, default=52.14, max_digits=4)),
                ('extra_downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_annual_downtime', models.CharField(blank=True, max_length=50, null=True)),
                ('impact_level', models.CharField(blank=True, max_length=50, null=True)),
                ('operational_level', models.IntegerField(blank=True, null=True)),
                ('availability_rank', models.IntegerField(blank=True, null=True)),
                ('availability_class', models.IntegerField(blank=True, null=True)),
                ('sites', models.ManyToManyField(blank=True, related_name='operational_requirements', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
